FROM ghcr.io/eeems/rm-qemu:latest

RUN bash -e <<EOT
  export DEBIAN_FRONTEND="noninteractive"
  apt-get update
  apt-get dist-upgrade -y --no-install-recommends
  apt-get install -y --no-install-recommends \
    gcc \
    xvfb \
    libc6-dev \
    coreutils \
    wget \
    zsync \
    git \
    make \
    xauth \
    ca-certificates \
    patchelf
  apt-get clean
  rm -rf /var/lib/apt/lists/*
EOT

RUN <<'EOT'
  set -e
  QS_SHA=9b30a89a3133b133577a411a269f1256db031955
  wget \
    --retry-connrefused \
    --tries=30 \
    "https://raw.githubusercontent.com/pkgforge-dev/Anylinux-AppImages/${QS_SHA}/useful-tools/quick-sharun.sh" \
    --output-document=/usr/bin/quick-sharun
  chmod +x /usr/bin/quick-sharun
  U2A_SHA=56052b1940d6a4f699169c8cc7f74ad36607cf53
  wget \
    --retry-connrefused \
    --tries=30 \
    "https://raw.githubusercontent.com/pkgforge-dev/Anylinux-AppImages/${U2A_SHA}/useful-tools/uruntime2appimage.sh" \
    --output-document=/usr/bin/uruntime2appimage
  chmod +x /usr/bin/uruntime2appimage
EOT

# removed ln-wrapper
COPY entrypoint /usr/bin
COPY bin/. /usr/local/bin/

RUN <<'EOT'
  set -e
  ln -sf /usr/bin/sha256sum /usr/local/bin/sha256sum
  ln -sf /usr/bin/ln /usr/local/bin/ln
EOT

ENTRYPOINT [ "/usr/bin/entrypoint" ]
